# Generated by Django 5.2.6 on 2025-09-15 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raison", models.CharField(max_length=100)),
                ("nif", models.CharField(max_length=100)),
                ("adresse", models.CharField(max_length=100)),
                ("mail", models.CharField(blank=True, max_length=100, null=True)),
                ("telephone", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Prestation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("designation", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("statut", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contenu", models.TextField()),
                (
                    "prestation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Trackerapp.prestation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Projet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("intitule", models.CharField(max_length=100)),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField()),
                ("statut", models.BooleanField(default=False)),
                (
                    "qr_code",
                    models.ImageField(blank=True, null=True, upload_to="QR_codes/"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Trackerapp.client",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="prestation",
            name="projet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Trackerapp.projet"
            ),
        ),
        migrations.CreateModel(
            name="Utilisateur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "poste",
                    models.CharField(
                        choices=[
                            ("AD", "AD"),
                            ("CDM", "CDM"),
                            ("CDN", "CDN"),
                            ("CDV", "CDV"),
                            ("CG", "CG"),
                            ("DG", "DG"),
                            ("Employé", "Employé"),
                            ("VIP", "VIP"),
                        ],
                        default="Employé",
                        max_length=30,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            (
                                "Administration - Comptabilite - Finance",
                                "Administration - Comptabilite - Finance",
                            ),
                            ("Direction Generale", "Direction Generale"),
                            (
                                "Marketing et Developpement",
                                "Marketing et Developpement",
                            ),
                            ("Transformation Numerique", "Transformation Numerique"),
                            (
                                "Visibilite - Infrastructure - Production",
                                "Visibilite - Infrastructure - Production",
                            ),
                            ("Ventes et Clientele", "Ventes et Clientele"),
                        ],
                        default="Employé",
                        max_length=50,
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
