# Generated by Django 5.2.6 on 2025-09-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Trackerapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projet",
            name="direction",
            field=models.CharField(
                choices=[
                    (
                        "Administration - Comptabilite - Finance",
                        "Administration - Comptabilite - Finance",
                    ),
                    ("Direction Generale", "Direction Generale"),
                    ("Marketing et Developpement", "Marketing et Developpement"),
                    ("Transformation Numerique", "Transformation Numerique"),
                    (
                        "Visibilite - Infrastructure - Production",
                        "Visibilite - Infrastructure - Production",
                    ),
                    ("Ventes et Clientele", "Ventes et Clientele"),
                ],
                default="Direction Generale",
                max_length=100,
            ),
        ),
    ]
