# Generated by Django 5.2.6 on 2025-09-19 17:28

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Trackerapp", "0002_projet_direction"),
    ]

    operations = [
        migrations.CreateModel(
            name="Questionnaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lien", models.URLField(blank=True, null=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "projet",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questionnaire",
                        to="Trackerapp.projet",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReponseQuestionnaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_reponse", models.DateTimeField(auto_now_add=True)),
                ("r1", models.BooleanField(default=False)),
                (
                    "r2",
                    multiselectfield.db.fields.MultiSelectField(
                        blank=True,
                        choices=[
                            ("location", "Location panneaux"),
                            ("confection", "Confection support de communication"),
                            ("evenementiel", "Événementiel"),
                            ("etude", "Étude de marché"),
                            ("impression", "Impression/production de gadgets"),
                            ("media", "Travaux médias"),
                            ("autres", "Autres (précisez)"),
                        ],
                        max_length=100,
                    ),
                ),
                ("r2_autre", models.CharField(blank=True, max_length=255, null=True)),
                ("r3", models.BooleanField(default=False)),
                ("r3_non", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "r4",
                    multiselectfield.db.fields.MultiSelectField(
                        blank=True,
                        choices=[
                            ("Qualité promise", "Qualité promise"),
                            (
                                "Délais de livraison promis ",
                                "Délais de livraison promis ",
                            ),
                            (
                                "Respect des engagements de l’agence",
                                "Respect des engagements de l’agence",
                            ),
                        ],
                        max_length=100,
                    ),
                ),
                ("r5", models.BooleanField(default=False)),
                ("r5_raison", models.CharField(blank=True, max_length=255, null=True)),
                ("r6", models.BooleanField(default=False)),
                ("r6_raison", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "questionnaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reponses",
                        to="Trackerapp.questionnaire",
                    ),
                ),
            ],
        ),
    ]
