# Generated by Django 5.2.6 on 2025-10-02 11:30

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trackerapp', '0003_questionnaire_reponsequestionnaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='date_fin',
        ),
        migrations.AddField(
            model_name='projet',
            name='utilisateur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Trackerapp.utilisateur'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reponsequestionnaire',
            name='fonction',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reponsequestionnaire',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reponsequestionnaire',
            name='raison',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reponsequestionnaire',
            name='telephone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reponsequestionnaire',
            name='r1',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='reponsequestionnaire',
            name='r3',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='reponsequestionnaire',
            name='r5',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='reponsequestionnaire',
            name='r6',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Papi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lien', models.URLField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='papi', to='Trackerapp.client')),
            ],
        ),
        migrations.CreateModel(
            name='ReponsePapi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reponse', models.DateTimeField(auto_now_add=True)),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('raison', models.CharField(blank=True, max_length=100, null=True)),
                ('fonction', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone', models.CharField(blank=True, max_length=100, null=True)),
                ('r1', models.BooleanField(default=True)),
                ('r2', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('location', 'Location panneaux'), ('confection', 'Confection support de communication'), ('evenementiel', 'Événementiel'), ('etude', 'Étude de marché'), ('impression', 'Impression/production de gadgets'), ('media', 'Travaux médias'), ('autres', 'Autres (précisez)')], max_length=100)),
                ('r2_autre', models.CharField(blank=True, max_length=255, null=True)),
                ('r3', models.BooleanField(default=True)),
                ('r3_non', models.CharField(blank=True, max_length=255, null=True)),
                ('r4', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Qualité promise', 'Qualité promise'), ('Délais de livraison promis ', 'Délais de livraison promis '), ('Respect des engagements de l’agence', 'Respect des engagements de l’agence')], max_length=100)),
                ('r5', models.BooleanField(default=True)),
                ('r5_raison', models.CharField(blank=True, max_length=255, null=True)),
                ('r6', models.BooleanField(default=True)),
                ('r6_raison', models.CharField(blank=True, max_length=255, null=True)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponsespapi', to='Trackerapp.papi')),
            ],
        ),
    ]
