# Generated by Django 5.2.6 on 2025-10-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trackerapp', '0004_remove_projet_date_fin_projet_utilisateur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestation',
            name='charge',
            field=models.CharField(choices=[('Administration - Comptabilite - Finance', 'Administration - Comptabilite - Finance'), ('Marketing et Developpement', 'Marketing et Developpement'), ('Transformation Numerique', 'Transformation Numerique'), ('Visibilite - Infrastructure - Production', 'Visibilite - Infrastructure - Production'), ('Ventes et Clientele', 'Ventes et Clientele')], default='Ventes et Clientele', max_length=50),
        ),
    ]
