# Generated by Django 5.2.6 on 2025-10-28 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trackerapp', '0005_prestation_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='auteur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Trackerapp.utilisateur'),
            preserve_default=False,
        ),
    ]
