# Generated by Django 5.2.6 on 2025-11-04 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trackerapp', '0006_note_auteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestation',
            name='date_fin',
            field=models.DateField(default=datetime.date(2025, 11, 4)),
            preserve_default=False,
        ),
    ]
